export default {
  GET_POKEMON_IMAGE_LIST_REQUEST: "GET_POKEMON_IMAGE_LIST_REQUEST",
  GET_POKEMON_IMAGE_LIST_SUCCESS: "GET_POKEMON_IMAGE_LIST_SUCCESS",
  GET_POKEMON_IMAGE_LIST_FAILURE: "GET_POKEMON_IMAGE_LIST_FAILURE",
};
