export default {
  GET_POKEMON_DETAIL_REQUEST: "GET_POKEMON_DETAIL_REQUEST",
  GET_POKEMON_DETAIL_SUCCESS: "GET_POKEMON_DETAIL_SUCCESS",
  GET_POKEMON_DETAIL_FAILURE: "GET_POKEMON_DETAIL_FAILURE",
};
